version: '3'
services:
  backend:
    build:
      context: .
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "5000:5000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
