version: '3'
services:
  backend:
    build:
      context: ./src/main/java/com/example/expensetracker/expensetracker
    ports:
      - "8080:8080"
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
